export type FoodsData = {
  id: number;
  title: string;
  foodName: string;
  description: string;
  category: string;
  time: number; // minutes
  image: any;
  price: number;
  favorite: boolean;
};

export const foods: FoodsData[] = [
  {
    id: 1,
    title: "Classic Tiramisu",
    foodName: "Tiramisu",
    description: "Classic Italian tiramisu with coffee dusting - a perfect blend of coffee and cream.",
  category: "Italian",
    time: 40,
    image: require("@/assets/foods/tiramisu.jpg"),
    price: 8.99,
    favorite: true,
  },
  {
    id: 2,
    title: "Creamy Tuscan Chicken Pasta",
    foodName: "Tuscan Pasta",
    description: "Rich and creamy Tuscan-style chicken pasta with spinach and sun-dried tomatoes.",
  category: "Italian",
    time: 30,
    image: require("@/assets/foods/tuscan-pasta.jpg"),
    price: 14.99,
    favorite: true,
  },
  {
    id: 3,
    title: "Homemade Italian Bread",
    foodName: "Italian Bread",
    description: "Easy to prepare, authentic Italian bread with a perfect crust.",
  category: "Bread",
    time: 180,
    image: require("@/assets/foods/italian-bread.jpg"),
    price: 6.50,
    favorite: false,
  },
  {
    id: 4,
    title: "French Baguettes",
    foodName: "Baguettes",
    description: "Classic crusty French baguettes - perfectly crisp outside, soft inside.",
  category: "Bread",
    time: 180,
    image: require("@/assets/foods/french-baguettes.jpg"),
    price: 4.99,
    favorite: true,
  },
  {
    id: 5,
    title: "Homemade Naan Bread",
    foodName: "Naan Bread",
    description: "Soft and fluffy homemade naan bread - perfect with any curry.",
  category: "Bread",
    time: 45,
    image: require("@/assets/foods/naan-bread.jpg"),
    price: 3.99,
    favorite: false,
  },
  {
    id: 6,
    title: "Rosemary Garlic Focaccia",
    foodName: "Focaccia",
    description: "Aromatic rosemary garlic focaccia bread - Italian flat bread at its best.",
  category: "Bread",
    time: 120,
    image: require("@/assets/foods/focaccia.jpg"),
    price: 7.50,
    favorite: true,
  },
  {
    id: 7,
    title: "Dried Vegetable Soup Mix",
    foodName: "Vegetable Soup",
    description: "A pantry-friendly dried vegetable soup mix — easy to stash and quick to cook.",
  category: "Soup",
    time: 15,
    image: require("@/assets/foods/vegetable-soup.jpg"),
    price: 5.50,
    favorite: false,
  },
  {
    id: 8,
    title: "Blueberry Cupcakes",
    foodName: "White Chocolate Blueberry Cupcakes",
    description: "Delightful white chocolate cupcakes studded with fresh blueberries.",
  category: "Dessert",
    time: 45,
    image: require("@/assets/foods/blueberry-cupcakes.jpg"),
    price: 3.99,
    favorite: true,
  },
  {
    id: 9,
    title: "Strawberry Cheesecake Parfaits",
    foodName: "No-Bake Parfaits",
    description: "No-bake strawberry cheesecake parfaits - layers of creamy delight.",
  category: "Dessert",
    time: 30,
    image: require("@/assets/foods/strawberry-parfait.jpg"),
    price: 6.99,
    favorite: true,
  },
  {
    id: 10,
    title: "Coffee Panna Cotta",
    foodName: "Panna Cotta al Caffè",
    description: "Silky coffee panna cotta with rich cocoa sauce.",
  category: "Dessert",
    time: 240,
    image: require("@/assets/foods/coffee-panna-cotta.jpg"),
    price: 8.50,
    favorite: false,
  },
  {
    id: 11,
    title: "Vanilla Panna Cotta",
    foodName: "Classic Panna Cotta",
    description: "Classic Italian vanilla panna cotta - elegant and simple.",
  category: "Dessert",
    time: 240,
    image: require("@/assets/foods/vanilla-panna-cotta.jpg"),
    price: 7.99,
    favorite: false,
  },
  {
    id: 12,
    title: "Hazelnut Iced Coffee",
    foodName: "Caramel Hazelnut Coffee",
    description: "Refreshing caramel hazelnut iced coffee - perfect summer drink.",
  category: "Coffee",
    time: 10,
    image: require("@/assets/foods/hazelnut-coffee.jpg"),
    price: 4.99,
    favorite: true,
  },
  {
    id: 13,
    title: "Decadent Coffee Mousse",
    foodName: "Coffee Mousse",
    description: "Smooth and airy coffee mousse - a coffee lover's dream dessert.",
  category: "Coffee",
    time: 180,
    image: require("@/assets/foods/coffee-mousse.jpg"),
    price: 6.99,
    favorite: false,
  },
  {
    id: 14,
    title: "Homemade Beef Stew",
    foodName: "Beef Stew",
    description: "Slow-simmered beef with carrots and potatoes — classic comfort food.",
  category: "Italian",
    time: 90,
    image: require("@/assets/foods/beef-stew.jpg"),
    price: 14.99,
    favorite: true,
  },
  {
    id: 15,
    title: "Sweet & Spicy Chicken",
    foodName: "Sticky Chicken",
    description: "Crispy chicken glazed in a sweet and spicy sticky sauce — perfect over rice.",
  category: "Italian",
    time: 35,
    image: require("@/assets/foods/sticky-chicken.jpg"),
    price: 11.99,
    favorite: false,
  },
  {
    id: 16,
    title: "Grilled Lemon Butter Salmon",
    foodName: "Grilled Salmon",
    description: "Perfectly grilled salmon with bright lemon butter sauce.",
  category: "Italian",
    time: 25,
    image: require("@/assets/foods/grilled-salmon.jpg"),
    price: 16.99,
    favorite: true,
  },
  {
    id: 17,
    title: "Crispy Air-Fryer Salmon",
    foodName: "Air-Fryer Salmon",
    description: "Quick and easy air-fryer salmon - crispy outside, tender inside.",
  category: "Italian",
    time: 15,
    image: require("@/assets/foods/airfryer-salmon.jpg"),
    price: 15.99,
    favorite: false,
  },
  {
    id: 18,
    title: "Starbucks Banana Bread",
    foodName: "Banana Bread",
    description: "Moist, tender banana bread — perfect with coffee.",
    category: "Bread",
    time: 70,
    image: require("@/assets/foods/banana-bread.jpg"),
    price: 4.5,
    favorite: false,
  },
  {
    id: 19,
    title: "Beef Special",
    foodName: "Beef Special",
    description: "Savory chef-style beef special with rich gravy.",
    category: "Italian",
    time: 100,
    image: require("@/assets/foods/beef-special.jpg"),
    price: 15.99,
    favorite: false,
  },
  {
    id: 20,
    title: "Tuscan Chicken (Grilled)",
    foodName: "Tuscan Chicken",
    description: "Grilled Tuscan chicken tossed with herbs and tomatoes.",
    category: "Italian",
    time: 35,
    image: require("@/assets/foods/Tuscan Chicken Pasta.jpg"),
    price: 13.99,
    favorite: false,
  },
  {
    id: 21,
    title: "Chocolate Coffee Drink",
    foodName: "Chocolate Coffee",
    description: "A sweet chocolate coffee — great as a dessert drink.",
    category: "Coffee",
    time: 10,
    image: require("@/assets/foods/chocolate-coffee.jpg"),
    price: 3.99,
    favorite: false,
  },
  {
    id: 22,
    title: "Cinnamon Swirl Raisin",
    foodName: "Cinnamon Raisin Bread",
    description: "Soft cinnamon-raisin loaf with a sweet swirl.",
    category: "Bread",
    time: 90,
    image: require("@/assets/foods/cinnamon-raisin.jpg"),
    price: 5.5,
    favorite: false,
  },
  {
    id: 23,
    title: "Creamy Recipe",
    foodName: "Creamy Dish",
    description: "A creamy, comforting recipe — great for weeknights.",
    category: "Dessert",
    time: 40,
    image: require("@/assets/foods/creamy-recipe.jpg"),
    price: 7.5,
    favorite: false,
  },
  {
    id: 24,
    title: "First Watch Special",
    foodName: "Breakfast Special",
    description: "A hearty breakfast-style dish to start the day.",
    category: "Italian",
    time: 20,
    image: require("@/assets/foods/first-watch.jpg"),
    price: 6.99,
    favorite: false,
  },
  {
    id: 25,
    title: "Cookie Lovers",
    foodName: "Cookies",
    description: "Assorted cookies — sweet and chewy.",
    category: "Dessert",
    time: 30,
    image: require("@/assets/foods/Hello, cookie lovers! Today, I'm delighted to….jpg"),
    price: 2.99,
    favorite: false,
  },
  {
    id: 26,
    title: "Mini Lemon Treats",
    foodName: "Mini Lemon",
    description: "Zesty mini lemon desserts — bright and tart.",
    category: "Dessert",
    time: 25,
    image: require("@/assets/foods/mini-lemon.jpg"),
    price: 3.5,
    favorite: false,
  },
  {
    id: 27,
    title: "Moist Banana Cake",
    foodName: "Moist Banana",
    description: "Super moist banana cake — decadent and soft.",
    category: "Bread",
    time: 60,
    image: require("@/assets/foods/moist-banana.jpg"),
    price: 4.99,
    favorite: false,
  },
  {
    id: 28,
    title: "Ninja Coffee",
    foodName: "Ninja Coffee",
    description: "Quick brewed coffee for busy mornings.",
    category: "Coffee",
    time: 5,
    image: require("@/assets/foods/ninja-coffee.jpg"),
    price: 2.99,
    favorite: false,
  },
  {
    id: 29,
    title: "Protein Tiramisu",
    foodName: "Protein Tiramisu",
    description: "A higher-protein take on classic tiramisu.",
    category: "Dessert",
    time: 45,
    image: require("@/assets/foods/protein-tiramisu.jpg"),
    price: 9.5,
    favorite: false,
  },
  {
    id: 30,
    title: "Quick Bread",
    foodName: "Quick Bread",
    description: "A fast loaf recipe for last-minute baking.",
    category: "Bread",
    time: 35,
    image: require("@/assets/foods/quick-bread.jpg"),
    price: 3.99,
    favorite: false,
  },
  {
    id: 31,
    title: "Classic Strawberry Pie",
    foodName: "Strawberry Pie",
    description: "Fresh strawberry pie — a summer classic.",
    category: "Dessert",
    time: 90,
    image: require("@/assets/foods/strawberry-pie.jpg"),
    price: 12.0,
    favorite: false,
  },
  {
    id: 32,
    title: "Promo Tuscan Pasta",
    foodName: "Tuscan Promo",
    description: "Promotional image for Tuscan chicken pasta (duplicate asset).",
    category: "Italian",
    time: 30,
    image: require("@/assets/foods/Tuscan Chicken Pasta.jpg"),
    price: 14.99,
    favorite: false,
  },
  {
    id: 33,
    title: "Vanilla Cupcakes",
    foodName: "Vanilla Cupcakes",
    description: "Simple vanilla cupcakes for any occasion.",
    category: "Dessert",
    time: 40,
    image: require("@/assets/foods/vanilla-cupcakes.jpg"),
    price: 3.5,
    favorite: false,
  },
  {
    id: 34,
    title: "No-bake Zesty Dessert",
    foodName: "Zesty No-bake",
    description: "No-bake zesty lemon dessert — quick and bright.",
    category: "Dessert",
    time: 20,
    image: require("@/assets/foods/zesty-nobake.jpg"),
    price: 5.0,
    favorite: false,
  },
  {
    id: 35,
    title: "Cafe Promo",
    foodName: "Cafe Promo",
    description: "Promotional cafe/coffee shot image.",
    category: "Coffee",
    time: 5,
    image: require("@/assets/foods/tiramisu-cold-brew.jpg"),
    price: 0,
    favorite: false,
  },
];